@extends('layouts.admin') @section('title','داشبورد | مدیریت اتوکار') @section('page_title','داشبورد') @section('content')
@php
$orderTotal=max(1,(int)$orderStatuses->sum('total')); $cursor=0; $segments=[];
foreach($orderStatuses as $index=>$row){$start=$cursor;$cursor+=((int)$row->total/$orderTotal)*100;$segments[]='hsl('.(($index*47)%360).' 65% 50%) '.$start.'% '.$cursor.'%';}
@endphp
<div class="admin-heading"><div><h1>نمای کلی فروشگاه</h1><p>فروش، سفارش، موجودی، صف و سلامت Providerها</p></div><span>{{ app(\App\Support\JalaliDate::class)->format(now()) }}</span></div>
<div class="admin-kpi-grid">@foreach([['فروش ۳۰ روز',number_format($kpis['sales']),'bi-cash-stack'],['تعداد سفارش',number_format($kpis['orders']),'bi-bag-check'],['سود ناخالص',number_format($kpis['gross_profit']??0),'bi-graph-up-arrow'],['موجودی کم',number_format($kpis['low_stock']),'bi-exclamation-triangle']] as $card)<div class="kpi-card"><div class="kpi-icon"><i class="bi {{ $card[2] }}"></i></div><div><span>{{ $card[0] }}</span><strong>{{ $card[1] }}</strong></div></div>@endforeach</div>
<div class="admin-two-col"><section class="admin-card"><div class="card-head"><h3>فروش روزانه</h3><span>۳۰ روز</span></div><div class="sales-bars" data-sales='@json($series)'>@php($maxSale=max(1,...array_column($series,'total')))@foreach($series as $point)<div class="sales-bar" title="{{ $point['day'] }}: {{ number_format($point['total']) }}" style="--value:{{ max(4,min(100,$point['total']/$maxSale*100)) }}%"></div>@endforeach</div></section><section class="admin-card"><div class="card-head"><h3>هشدار موجودی</h3><a href="{{ route('admin.inventory.index') }}">مشاهده انبار</a></div>@forelse($lowStock as $stock)<div class="stock-alert"><span>{{ $stock->name }}</span><b>{{ $stock->on_hand-$stock->reserved-$stock->damaged }}</b></div>@empty<p class="text-muted">هشداری وجود ندارد.</p>@endforelse</section></div>
<div class="row g-3 mt-1"><div class="col-lg-4"><section class="admin-card"><h3>وضعیت سفارش</h3><div class="d-flex align-items-center gap-3 flex-wrap"><div role="img" aria-label="نمودار سهم وضعیت سفارش‌ها" style="width:118px;height:118px;border-radius:50%;background:{{ $segments ? 'conic-gradient('.implode(',',$segments).')' : '#e9ecef' }};position:relative"><span style="position:absolute;inset:25%;border-radius:50%;background:var(--bs-body-bg,#fff);display:grid;place-items:center;font-weight:700">{{ $orderStatuses->sum('total') }}</span></div><div class="flex-grow-1">@foreach($orderStatuses as $index=>$row)<div class="d-flex justify-content-between py-1"><span><i class="d-inline-block rounded-circle me-1" style="width:9px;height:9px;background:hsl({{ ($index*47)%360 }} 65% 50%)"></i>{{ $row->status }}</span><b>{{ $row->total }}</b></div>@endforeach</div></div></section></div><div class="col-lg-4"><section class="admin-card"><h3>صف پردازش</h3><div>در صف: <b>{{ $queue['pending'] }}</b></div><div>ناموفق: <b>{{ $queue['failed'] }}</b></div><a href="{{ route('admin.operations-health.index') }}">عملیات و سلامت</a></section></div><div class="col-lg-4"><section class="admin-card"><h3>Providerها</h3>@forelse($providerHealth as $row)<div class="d-flex justify-content-between py-1"><span>{{ $row->provider }}</span><span class="status-badge">{{ $row->status }}</span></div>@empty<small>Health Check اجرا نشده است.</small>@endforelse</section></div></div>
<section class="admin-card mt-3"><div class="card-head"><h3>آخرین سفارش‌ها</h3><a href="{{ route('admin.orders.index') }}">همه سفارش‌ها</a></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>شماره</th><th>وضعیت</th><th>مبلغ</th><th>تاریخ</th></tr></thead><tbody>@foreach($orders as $order)<tr><td><a href="{{ route('admin.orders.show',$order->id) }}">{{ $order->number }}</a></td><td><span class="status-badge">{{ $order->status }}</span></td><td>{{ number_format($order->grand_total) }}</td><td>{{ app(\App\Support\JalaliDate::class)->format(\Illuminate\Support\Carbon::parse($order->created_at)) }}</td></tr>@endforeach</tbody></table></div></section>@endsection
