@extends('layouts.admin')
@section('title','تنظیمات | اتوکار') @section('page_title','تنظیمات')
@section('content')
@php($repo=app(\App\Services\Settings\SettingsRepository::class))
<div class="admin-heading"><div><h1>تنظیمات فروشگاه</h1><p>عمومی، امنیت، فاکتور و Providerهای پیش‌فرض؛ Secretهای API از فرم اختصاصی Provider مدیریت می‌شوند.</p></div></div>
<form class="admin-card settings-form" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('put')
<h4>عمومی</h4><div class="row g-3"><div class="col-md-6"><label>نام سایت</label><input class="form-control" name="site_name" value="{{ old('site_name',$repo->get('site.name','AutoCar')) }}"></div><div class="col-md-6"><label>تلفن پشتیبانی</label><input class="form-control" name="support_phone" value="{{ $repo->get('site.support_phone') }}"></div><div class="col-md-4"><label>حداقل سفارش</label><input class="form-control" type="number" name="minimum_order" value="{{ $repo->get('order.minimum',0) }}"></div><div class="col-md-4"><label>درگاه پیش‌فرض</label><select class="form-select" name="default_gateway">@foreach(\App\Domain\Payment\Services\PaymentService::ONLINE_GATEWAYS as $g)<option value="{{ $g }}" @selected($repo->get('payments.default_gateway','zarinpal')===$g)>{{ $g }}</option>@endforeach</select></div><div class="col-md-4"><label>پیامک پیش‌فرض</label><select class="form-select" name="default_sms_provider">@foreach(array_merge(['kavenegar'],\App\Domain\Sms\Services\SmsService::CONFIGURABLE_PROVIDERS) as $p)<option value="{{ $p }}" @selected($repo->get('sms.default_provider','kavenegar')===$p)>{{ $p }}</option>@endforeach</select></div></div>
<hr><h4>امنیت و نگهداری</h4><div class="row"><div class="col-md-6"><label class="form-check"><input class="form-check-input" name="maintenance" type="checkbox" value="1" @checked($repo->get('site.maintenance',false))> حالت تعمیر واقعی (HTTP 503)</label></div><div class="col-md-6"><label class="form-check"><input class="form-check-input" name="require_admin_2fa" type="checkbox" value="1" @checked($repo->get('security.require_admin_2fa',false))> الزام 2FA برای پنل مدیریت</label></div></div>
<hr><h4>اطلاعات فروشنده روی فاکتور</h4><div class="row g-3">@foreach(['seller_name'=>'نام حقوقی/فروشنده','seller_national_id'=>'شناسه ملی','seller_economic_code'=>'کد اقتصادی','seller_registration_number'=>'شماره ثبت','seller_phone'=>'تلفن','seller_postal_code'=>'کدپستی'] as $key=>$label)<div class="col-md-4"><label>{{ $label }}</label><input class="form-control" name="{{ $key }}" value="{{ $repo->get('invoice.'.$key) }}"></div>@endforeach<div class="col-12"><label>آدرس فروشنده</label><textarea class="form-control" name="seller_address">{{ $repo->get('invoice.seller_address') }}</textarea></div></div>
<button class="btn btn-primary mt-4">ذخیره تنظیمات</button></form>
@endsection
