@extends('layouts.admin')
@section('title','برندها | اتوکار')
@section('page_title','برند قطعات')
@section('content')
<div class="row g-4">
    <div class="col-xl-8"><div class="admin-card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>لوگو</th><th>نام</th><th>Slug</th><th>کشور</th><th>محصول</th><th>فعال</th><th></th></tr></thead><tbody>
    @foreach($brands as $brand)
        <tr><td>@if($brand->logo_path)<img src="{{ asset('storage/'.$brand->logo_path) }}" alt="" style="width:54px;height:42px;object-fit:contain">@endif</td><td><b>{{ $brand->name }}</b><br><small>{{ $brand->name_en }}</small></td><td><code>{{ $brand->slug }}</code></td><td>{{ $brand->country_code }}</td><td>{{ $brand->products_count }}</td><td>{{ $brand->is_active?'بله':'خیر' }}</td><td class="text-nowrap"><a class="btn btn-sm btn-light" target="_blank" href="{{ route('brand.show',$brand) }}">نمایش</a><form class="d-inline" method="post" action="{{ route('admin.brands.destroy',$brand) }}" onsubmit="return confirm('برند حذف شود؟')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger">حذف</button></form></td></tr>
        <tr><td colspan="7"><details><summary class="btn btn-sm btn-outline-secondary">ویرایش {{ $brand->name }}</summary><form class="row g-2 mt-2" method="post" enctype="multipart/form-data" action="{{ route('admin.brands.update',$brand) }}">@csrf @method('put')<div class="col-md-4"><label>نام فارسی</label><input class="form-control" name="name" value="{{ $brand->name }}" required></div><div class="col-md-4"><label>نام انگلیسی</label><input class="form-control" name="name_en" value="{{ $brand->name_en }}"></div><div class="col-md-4"><label>Slug</label><input class="form-control" name="slug" value="{{ $brand->slug }}"></div><div class="col-md-4"><label>کشور</label><input class="form-control" name="country_code" value="{{ $brand->country_code }}" maxlength="2"></div><div class="col-md-8"><label>لوگوی جدید</label><input class="form-control" type="file" name="logo" accept="image/jpeg,image/png,image/webp"></div><div class="col-12"><label>توضیحات</label><textarea class="form-control" name="description" rows="3">{{ $brand->description }}</textarea></div><div class="col-md-6"><label>Meta title</label><input class="form-control" name="meta_title" value="{{ $brand->meta_title }}"></div><div class="col-md-6"><label>Meta description</label><textarea class="form-control" name="meta_description" rows="2">{{ $brand->meta_description }}</textarea></div><div class="col-12"><label><input type="checkbox" name="is_active" value="1" @checked($brand->is_active)> فعال</label></div><div class="col-12"><button class="btn btn-primary">ذخیره برند</button></div></form></details></td></tr>
    @endforeach
    </tbody></table></div>{{ $brands->links() }}</div></div>
    <div class="col-xl-4"><div class="admin-card"><h4>برند جدید</h4><form method="post" enctype="multipart/form-data" action="{{ route('admin.brands.store') }}">@csrf<label>نام فارسی</label><input class="form-control mb-2" name="name" required><label>نام انگلیسی</label><input class="form-control mb-2" name="name_en"><label>Slug</label><input class="form-control mb-2" name="slug"><label>کشور</label><input class="form-control mb-2" name="country_code" maxlength="2" placeholder="IR / KR / DE"><label>لوگو</label><input class="form-control mb-2" type="file" name="logo" accept="image/jpeg,image/png,image/webp"><label>توضیح</label><textarea class="form-control mb-2" name="description"></textarea><label>Meta title</label><input class="form-control mb-2" name="meta_title"><label>Meta description</label><textarea class="form-control mb-2" name="meta_description"></textarea><label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked> فعال</label><button class="btn btn-primary w-100">ایجاد</button></form></div></div>
</div>
@endsection
