[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
priority=5

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=10

[program:queue]
command=php /var/www/html/artisan queue:work --sleep=2 --tries=3 --timeout=90 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
process_name=%(program_name)s_%(process_num)02d
priority=20

[program:scheduler]
command=/bin/sh -c 'while true; do php /var/www/html/artisan schedule:run --no-interaction; sleep 60; done'
autostart=true
autorestart=true
priority=30
