<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','مدیریت اتوکار')</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.rtl.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"><link rel="stylesheet" href="{{ route('assets.css') }}"><link rel="stylesheet" href="{{ route('assets.extensions.css') }}"></head><body class="admin-body"><div class="admin-shell"><aside class="admin-sidebar" data-admin-sidebar><a class="ac-brand admin-logo" href="{{ route('admin.dashboard') }}">AUTO<span>CAR</span></a><div class="sidebar-caption">مدیریت فروشگاه</div><nav>
<a @class(['active'=>request()->routeIs('admin.dashboard')]) href="{{ route('admin.dashboard') }}"><i class="bi bi-speedometer2"></i> داشبورد</a>
<a @class(['active'=>request()->routeIs('admin.orders.*')]) href="{{ route('admin.orders.index') }}"><i class="bi bi-box-seam"></i> سفارش‌ها</a>
<a @class(['active'=>request()->routeIs('admin.products.*')]) href="{{ route('admin.products.index') }}"><i class="bi bi-grid"></i> محصولات</a>
<a @class(['active'=>request()->routeIs('admin.categories.*')]) href="{{ route('admin.categories.index') }}"><i class="bi bi-diagram-3"></i> دسته‌بندی‌ها</a>
<a @class(['active'=>request()->routeIs('admin.brands.*')]) href="{{ route('admin.brands.index') }}"><i class="bi bi-award"></i> برندها</a>
<a @class(['active'=>request()->routeIs('admin.vehicles.*')]) href="{{ route('admin.vehicles.index') }}"><i class="bi bi-car-front"></i> خودرو و سازگاری</a>
<a @class(['active'=>request()->routeIs('admin.inventory.*')]) href="{{ route('admin.inventory.index') }}"><i class="bi bi-boxes"></i> انبار</a>
<a @class(['active'=>request()->routeIs('admin.procurement.*')]) href="{{ route('admin.procurement.index') }}"><i class="bi bi-truck"></i> تأمین و سفارش خرید</a>
<a @class(['active'=>request()->routeIs('admin.shipping.*')]) href="{{ route('admin.shipping.index') }}"><i class="bi bi-send"></i> ارسال و Fulfillment</a>
<a @class(['active'=>request()->routeIs('admin.rma.*')]) href="{{ route('admin.rma.index') }}"><i class="bi bi-arrow-counterclockwise"></i> RMA و بازپرداخت</a>
<a @class(['active'=>request()->routeIs('admin.catalog-operations.*')]) href="{{ route('admin.catalog-operations.index') }}"><i class="bi bi-filetype-csv"></i> ورود/خروج کالا</a>
<a @class(['active'=>request()->routeIs('admin.customers.*')]) href="{{ route('admin.customers.index') }}"><i class="bi bi-people"></i> مشتریان و CRM</a>
<a @class(['active'=>request()->routeIs('admin.wholesale.*')]) href="{{ route('admin.wholesale.index') }}"><i class="bi bi-building"></i> فروش عمده B2B</a>
<a @class(['active'=>request()->routeIs('admin.promotions.*')]) href="{{ route('admin.promotions.index') }}"><i class="bi bi-percent"></i> تخفیف و کوپن</a>
<a @class(['active'=>request()->routeIs('admin.marketing.*')]) href="{{ route('admin.marketing.index') }}"><i class="bi bi-megaphone"></i> کمپین</a>
<a @class(['active'=>request()->routeIs('admin.sms.*')]) href="{{ route('admin.sms.index') }}"><i class="bi bi-chat-square-text"></i> پیامک</a>
<a @class(['active'=>request()->routeIs('admin.payments.*')]) href="{{ route('admin.payments.index') }}"><i class="bi bi-credit-card"></i> پرداخت‌ها</a>
<a @class(['active'=>request()->routeIs('admin.support.*')]) href="{{ route('admin.support.index') }}"><i class="bi bi-headset"></i> پشتیبانی</a>
<a @class(['active'=>request()->routeIs('admin.editorial.*')]) href="{{ route('admin.editorial.index') }}"><i class="bi bi-file-earmark-text"></i> محتوا و بلاگ</a>
<a @class(['active'=>request()->routeIs('admin.banners.*')]) href="{{ route('admin.banners.index') }}"><i class="bi bi-images"></i> بنرها</a>
<a @class(['active'=>request()->routeIs('admin.moderation.*')]) href="{{ route('admin.moderation.index') }}"><i class="bi bi-chat-square-check"></i> نظرات و پرسش‌ها</a>
<a @class(['active'=>request()->routeIs('admin.search-seo.*')]) href="{{ route('admin.search-seo.index') }}"><i class="bi bi-search"></i> جست‌وجو و SEO</a>
<a @class(['active'=>request()->routeIs('admin.menu.*')]) href="{{ route('admin.menu.index') }}"><i class="bi bi-menu-button-wide"></i> مگامنو</a>
<a @class(['active'=>request()->routeIs('admin.reports.*')]) href="{{ route('admin.reports.index') }}"><i class="bi bi-bar-chart"></i> گزارش‌ها</a>
<a @class(['active'=>request()->routeIs('admin.security.*')]) href="{{ route('admin.security.index') }}"><i class="bi bi-shield-lock"></i> امنیت و دسترسی</a>
<a @class(['active'=>request()->routeIs('admin.settings.*')]) href="{{ route('admin.settings.index') }}"><i class="bi bi-gear"></i> تنظیمات</a>
</nav></aside><main class="admin-main"><header class="admin-topbar"><button class="admin-menu-btn" data-admin-menu><i class="bi bi-list"></i></button><div><small>پنل مدیریت</small><b>@yield('page_title','AutoCar')</b></div><div class="admin-user"><i class="bi bi-bell"></i><span>{{ auth()->user()->name }}</span><a href="{{ route('account.2fa.setup') }}" title="2FA"><i class="bi bi-shield-check"></i></a><a href="{{ route('home') }}" target="_blank"><i class="bi bi-box-arrow-up-left"></i></a></div></header><div class="admin-content">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</div></main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" defer></script><script src="{{ route('assets.js') }}" defer></script></body></html>
