@extends('layouts.storefront')
@section('title','اتوکار | فروشگاه تخصصی قطعات و لوازم یدکی')
@section('content')
<section class="hero-section"><div class="container"><div class="hero-grid">
<div class="hero-copy"><span class="eyebrow">قطعه درست برای خودروی درست</span><h1>قطعات خودرو را با <span>سازگاری دقیق</span> انتخاب کنید</h1><p>خودرو را انتخاب کنید یا با نام قطعه، برند، SKU و کد OEM جست‌وجو کنید.</p><div class="d-flex gap-2 flex-wrap"><a class="btn btn-primary btn-lg" href="{{ route('search') }}">مشاهده قطعات</a><a class="btn btn-light btn-lg" href="#vehicle-picker">انتخاب خودرو</a></div><div class="hero-stats"><div><strong>کد فنی</strong><span>جست‌وجوی دقیق OEM</span></div><div><strong>اصالت</strong><span>وضعیت شفاف کالا</span></div><div><strong>Fitment</strong><span>سازگاری با خودرو</span></div></div></div>
<div class="hero-visual"><div class="car-silhouette"><i class="bi bi-car-front-fill"></i></div><div class="floating-card one"><i class="bi bi-check-circle-fill"></i><div><b>سازگار با خودرو</b><small>قبل از افزودن به سبد</small></div></div><div class="floating-card two"><i class="bi bi-upc-scan"></i><div><b>OEM / SKU</b><small>جست‌وجوی سریع قطعه</small></div></div></div>
</div>
@if($heroBanners->isNotEmpty())<div class="hero-banner-stack">@foreach($heroBanners as $banner)<a class="hero-banner" href="{{ route('banners.click',$banner) }}" data-banner-impression="{{ route('banners.impression',$banner) }}"><picture>@if($banner->mobile_image_path)<source media="(max-width: 767px)" srcset="{{ asset('storage/'.$banner->mobile_image_path) }}">@endif<img loading="{{ $loop->first?'eager':'lazy' }}" src="{{ asset('storage/'.$banner->image_path) }}" alt="{{ $banner->alt ?: $banner->name }}"></picture></a>@endforeach</div>@endif
</div></section>

@if($specialProducts->isNotEmpty())<div class="promo-ribbon"><div class="container"><i class="bi bi-lightning-charge-fill"></i><b>پیشنهادهای زمان‌دار اتوکار فعال است</b><span>قیمت نهایی به‌صورت خودکار تا پایان کمپین محاسبه می‌شود.</span></div></div>@endif

<section class="container vehicle-picker-section" id="vehicle-picker"><div class="vehicle-picker ac-surface"><div><span class="eyebrow">گاراژ هوشمند</span><h2>خودروی خود را انتخاب کنید</h2><p>بعد از انتخاب، قطعات سازگار با خودرو را راحت‌تر پیدا می‌کنید.</p></div><div class="vehicle-form" data-vehicle-picker><select class="form-select" data-vehicle-make><option value="">برند خودرو</option>@foreach($vehicleMakes as $make)<option value="{{ $make->id }}">{{ $make->name }}</option>@endforeach</select><select class="form-select" data-vehicle-model disabled><option>مدل</option></select><select class="form-select" data-vehicle-generation disabled><option>نسل</option></select><select class="form-select" data-vehicle-trim disabled><option>سال / تیپ</option></select><button class="btn btn-dark" type="button" data-vehicle-submit>نمایش قطعات سازگار</button></div></div></section>

@if($specialProducts->isNotEmpty())<section class="container section-block"><div class="section-heading"><div><span class="eyebrow">فروش ویژه</span><h2>پیشنهادهای محدود زمانی</h2></div><a href="{{ route('search') }}">مشاهده فروشگاه</a></div><div class="product-grid">@foreach($specialProducts as $product)@include('storefront.partials.product-card',['product'=>$product])@endforeach</div></section>@endif

<section class="container section-block"><div class="section-heading"><div><span class="eyebrow">دسترسی سریع</span><h2>دسته‌بندی قطعات</h2></div><a href="{{ route('search') }}">مشاهده همه <i class="bi bi-arrow-left"></i></a></div><div class="category-grid">@foreach($categories as $category)<a class="category-card" href="{{ route('category.show',$category) }}"><div class="category-icon"><i class="bi bi-gear-wide-connected"></i></div><strong>{{ $category->name }}</strong><span>مشاهده قطعات</span></a>@endforeach</div></section>

@if($middleBanners->isNotEmpty())<section class="container section-block"><div class="hero-banner-stack">@foreach($middleBanners as $banner)<a class="hero-banner" href="{{ route('banners.click',$banner) }}" data-banner-impression="{{ route('banners.impression',$banner) }}"><picture>@if($banner->mobile_image_path)<source media="(max-width: 767px)" srcset="{{ asset('storage/'.$banner->mobile_image_path) }}">@endif<img loading="lazy" src="{{ asset('storage/'.$banner->image_path) }}" alt="{{ $banner->alt ?: $banner->name }}"></picture></a>@endforeach</div></section>@endif

<section class="container section-block"><div class="section-heading"><div><span class="eyebrow">تازه‌ها</span><h2>قطعات پیشنهادی</h2></div><a href="{{ route('search') }}">همه محصولات</a></div><div class="product-grid">@foreach($products as $product)@include('storefront.partials.product-card',['product'=>$product])@endforeach</div></section>

<section class="brand-strip" id="brands"><div class="container"><div class="section-heading"><div><span class="eyebrow">برندهای معتبر</span><h2>برند قطعه</h2></div></div><div class="brand-grid">@foreach($brands as $brand)<a href="{{ route('brand.show',$brand) }}">@if($brand->logo_path)<img loading="lazy" src="{{ asset('storage/'.$brand->logo_path) }}" alt="{{ $brand->name }}">@endif<span>{{ $brand->name }}</span></a>@endforeach</div></div></section>

@if($bottomBanners->isNotEmpty())<section class="container section-block"><div class="hero-banner-stack">@foreach($bottomBanners as $banner)<a class="hero-banner" href="{{ route('banners.click',$banner) }}" data-banner-impression="{{ route('banners.impression',$banner) }}"><picture>@if($banner->mobile_image_path)<source media="(max-width: 767px)" srcset="{{ asset('storage/'.$banner->mobile_image_path) }}">@endif<img loading="lazy" src="{{ asset('storage/'.$banner->image_path) }}" alt="{{ $banner->alt ?: $banner->name }}"></picture></a>@endforeach</div></section>@endif
@endsection
